stages:
- name: compile
  steps:
  - runScriptConfig:
      image: 172.16.1.243/headmaster/maven:v1
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 172.16.1.243/headmaster/pipeline:v1
      pushRemote: true
      registry: 127.0.0.1:34072
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
